name: "Whisper (Norwegian)"
description: "Whisper models for Norwegian languages. Based on fine tuned Whisper models trained by NB-Ai-Lab (https://huggingface.co/NbAiLab)"
version: "0.1.0"
slug: "nbailab-tiny"
init: false
arch:
  - aarch64
  - amd64
  - i386
